packageExtensions:
  "@fastify/autoload@*":
    dependencies:
      fastify: "*"
  "@fastify/sensible@*":
    dependencies:
      fastify: "*"
  fastify-plugin@*:
    dependencies:
      fastify: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.js
