packageExtensions:
  "@fastify/formbody@*":
    dependencies:
      fastify: "*"
  "@fastify/passport@*":
    dependencies:
      fastify: "*"
      "@types/passport": "*"
  "@fastify/sensible@*":
    dependencies:
      fastify: "*"
  "@fastify/cookie@*":
    dependencies:
      fastify: "*"
  "@fastify/secure-session@*":
    dependencies:
      fastify: "*"
  "@fastify/cors@*":
    dependencies:
      fastify: "*"
  "@fastify/view@*":
    dependencies:
      fastify: "*"
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  fastify-plugin@*:
    dependencies:
      fastify: "*"
  "@prisma/client@*":
    dependencies:
      '.prisma': 'link:See "resolution" field of package.json'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
