packageExtensions:
  "@fastify/cookie@*":
    dependencies:
      fastify: "*"
  "@fastify/cors@*":
    dependencies:
      fastify: "*"
  "@fastify/formbody@*":
    dependencies:
      fastify: "*"
  "@fastify/passport@*":
    dependencies:
      "@types/passport": "*"
      fastify: "*"
  "@fastify/secure-session@*":
    dependencies:
      fastify: "*"
  "@fastify/sensible@*":
    dependencies:
      fastify: "*"
  "@fastify/view@*":
    dependencies:
      fastify: "*"
  "@prisma/client@*":
    dependencies:
      .prisma: "link:See \"resolution\" field of package.json"
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  fastify-plugin@*:
    dependencies:
      fastify: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-docker-build.cjs
    spec: "https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-docker-build.js"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
