version: "3.10"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=article-picker
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "15432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql
