-- CreateEnum
CREATE TYPE "ARTICLE_CONTENT_STATUS" AS ENUM ('LOADING', 'LOADED', 'FAILED', 'CUSTOMIZED');

-- AlterTable
ALTER TABLE "Article" ADD COLUMN "contentStatus" "ARTICLE_CONTENT_STATUS" NOT NULL DEFAULT 'LOADING';

UPDATE "Article" SET "contentStatus" = 'CUSTOMIZED';
